name: Autmmated frontend deployment on the production server
on:
  push:
    branches:
      - main

jobs:
  pull:
    name: Checking the code out
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Delete existing `.env` file
        run: rm .env
      - name: Building `.env` file
        run: |
          echo "NEXT_PUBLIC_SERVER_URL=${{ secrets.NEXT_PUBLIC_SERVER_URL }}" > .env
          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> .env
          echo "NEXT_PUBLIC_APIKEY=${{ secrets.NEXT_PUBLIC_APIKEY }}" >> .env
          echo "NEXT_PUBLIC_AUTHDOMAIN=${{ secrets.NEXT_PUBLIC_AUTHDOMAIN }}" >> .env
          echo "NEXT_PUBLIC_PROJECT_ID=${{ secrets.NEXT_PUBLIC_PROJECT_ID }}" >> .env
          echo "NEXT_PUBLIC_STORAGE_BUCKET=${{ secrets.SENTRY_AUTH_TOKEN }}" >> .env
          echo "NEXT_PUBLIC_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_MESSAGING_SENDER_ID }}" >> .env
          echo "NEXT_PUBLIC_APP_ID=${{ secrets.NEXT_PUBLIC_APP_ID }}" >> .env

      - name: Take down any compose
        run: docker compose -p ${{secrets.PROJECT_NAME}} down
        continue-on-error: true
      - name: Remove the unused containers
        run: docker container prune -f
      - name: Remove unused images
        run: docker image prune -a -f
      - name: Build `Docker` image
        run: docker compose -f ./compose/prod.compose.yaml build
      - name: Run the compose up
        run: docker compose -f ./compose/prod.compose.yaml -p ${{secrets.PROJECT_NAME}} up --detach
